name: Build from commit
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: wap
      uses: t-mart/wap-action@master
      with:
        release-type: 'none'

    - uses: actions/upload-artifact@v3
      with:
        name: ItemVersion-${{ github.sha }}.zip
        path: dist/*
